// Preserve source exporter implementation during extraction.
#![allow(clippy::redundant_closure)]

use std::fmt::Write as FmtWrite;
use std::io::Write;
use std::path::Path;

use crate::format::ExportFormat;

use crate::model::Instrument;
use crate::traits::{ExportError, FormatExporter};
use crate::util::sanitize_filename;

/// Exports instruments to Ableton Live Sampler format.
///
/// Generates a .adg (Ableton Device Group) file, which is a gzipped XML
/// containing a Sampler instrument with MultiSampleMap zone definitions.
pub struct AbletonExporter;

impl FormatExporter for AbletonExporter {
    fn format(&self) -> ExportFormat {
        ExportFormat::AbletonSampler
    }

    fn name(&self) -> &str {
        "Ableton Sampler"
    }

    fn samples_subdir(&self) -> Option<&'static str> {
        Some("Samples")
    }

    fn export(&self, instrument: &Instrument, output_dir: &Path) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        std::fs::create_dir_all(&dir)?;

        let xml = generate_adg_xml(instrument);

        // Ableton .adg files are gzipped XML
        let filename = format!("{}.adg", sanitize_filename(&instrument.name));
        let file = std::fs::File::create(dir.join(filename))?;
        let mut encoder = flate2::write::GzEncoder::new(file, flate2::Compression::default());
        encoder
            .write_all(xml.as_bytes())
            .map_err(|e| ExportError::Io(e))?;
        encoder.finish().map_err(|e| ExportError::Io(e))?;

        Ok(())
    }
}

fn generate_adg_xml(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples -->"#).unwrap();
    writeln!(
        xml,
        r#"<Ableton MajorVersion="5" MinorVersion="11.0" Creator="Multisamples">"#
    )
    .unwrap();
    writeln!(xml, r#"  <MultiSampler Id="0">"#).unwrap();
    writeln!(xml, r#"    <Player>"#).unwrap();
    writeln!(xml, r#"      <MultiSampleMap>"#).unwrap();
    writeln!(xml, r#"        <SampleParts>"#).unwrap();

    let mut part_id = 0;
    for group in &instrument.groups {
        for zone in &group.zones {
            writeln!(xml, r#"          <MultiSamplePart Id="{}" HasImportedSlicePoints="true" NeedsAnalysisData="true">"#, part_id).unwrap();
            writeln!(xml, r#"            <Selection>true</Selection>"#).unwrap();
            writeln!(
                xml,
                r#"            <FileName>Samples/{}</FileName>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(xml, r#"            <KeyRange>"#).unwrap();
            writeln!(xml, r#"              <Min Value="{}" />"#, zone.key_low).unwrap();
            writeln!(xml, r#"              <Max Value="{}" />"#, zone.key_high).unwrap();
            writeln!(
                xml,
                r#"              <CrossfadeMin Value="{}" />"#,
                zone.key_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"              <CrossfadeMax Value="{}" />"#,
                zone.key_high
            )
            .unwrap();
            writeln!(xml, r#"            </KeyRange>"#).unwrap();
            writeln!(xml, r#"            <VelocityRange>"#).unwrap();
            writeln!(
                xml,
                r#"              <Min Value="{}" />"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"              <Max Value="{}" />"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(
                xml,
                r#"              <CrossfadeMin Value="{}" />"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"              <CrossfadeMax Value="{}" />"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"            </VelocityRange>"#).unwrap();
            writeln!(xml, r#"            <RootKey Value="{}" />"#, zone.root_note).unwrap();
            writeln!(
                xml,
                r#"            <Detune Value="{}" />"#,
                zone.tune_cents as i32
            )
            .unwrap();
            writeln!(xml, r#"            <Volume Value="{:.2}" />"#, zone.gain_db).unwrap();
            writeln!(xml, r#"          </MultiSamplePart>"#).unwrap();
            part_id += 1;
        }
    }

    writeln!(xml, r#"        </SampleParts>"#).unwrap();
    writeln!(xml, r#"      </MultiSampleMap>"#).unwrap();
    writeln!(xml, r#"    </Player>"#).unwrap();
    writeln!(xml, r#"  </MultiSampler>"#).unwrap();
    writeln!(xml, r#"</Ableton>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn adg_xml_structure() {
        let inst = Instrument::builder("Ableton Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        let xml = generate_adg_xml(&inst);
        assert!(xml.contains("<Ableton"));
        assert!(xml.contains("<MultiSampler"));
        assert!(xml.contains("<MultiSamplePart"));
        assert!(xml.contains(r#"<RootKey Value="60""#));
    }

    #[test]
    fn export_creates_gzipped_adg() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("Live Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        AbletonExporter.export(&inst, dir.path()).unwrap();

        let adg = dir.path().join("Live Test").join("Live Test.adg");
        assert!(adg.exists());

        // Verify it's gzipped (starts with magic bytes 1f 8b)
        let data = std::fs::read(&adg).unwrap();
        assert_eq!(data[0], 0x1f);
        assert_eq!(data[1], 0x8b);
    }
}
