// Preserve source exporter implementation during extraction.
#![allow(clippy::collapsible_if)]

use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::format::ExportFormat;

use crate::model::{Instrument, LoopMode};
use crate::traits::{ExportError, FormatExporter};
use crate::util::sanitize_filename;

/// Exports instruments to DecentSampler .dspreset format.
pub struct DecentSamplerExporter;

impl FormatExporter for DecentSamplerExporter {
    fn format(&self) -> ExportFormat {
        ExportFormat::DecentSampler
    }

    fn name(&self) -> &str {
        "DecentSampler"
    }

    fn export(&self, instrument: &Instrument, output_dir: &Path) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        std::fs::create_dir_all(&dir)?;

        let xml = generate_dspreset(instrument);
        let filename = format!("{}.dspreset", sanitize_filename(&instrument.name));
        std::fs::write(dir.join(filename), xml)?;

        Ok(())
    }
}

fn generate_dspreset(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples -->"#).unwrap();
    writeln!(xml, r#"<DecentSampler>"#).unwrap();
    writeln!(xml, r#"  <groups>"#).unwrap();

    for group in &instrument.groups {
        writeln!(xml, r#"    <group name="{}">"#, group.name).unwrap();

        for zone in &group.zones {
            let mut attrs = format!(
                r#"path="samples/{}" rootNote="{}" loNote="{}" hiNote="{}""#,
                zone.sample_path.display(),
                zone.root_note,
                zone.key_low,
                zone.key_high,
            );

            if zone.velocity_low > 0 || zone.velocity_high < 127 {
                write!(
                    attrs,
                    r#" loVel="{}" hiVel="{}""#,
                    zone.velocity_low, zone.velocity_high
                )
                .unwrap();
            }

            if (zone.gain_db).abs() > 0.01 {
                write!(attrs, r#" volume="{:.1}dB""#, zone.gain_db).unwrap();
            }

            if (zone.tune_cents).abs() > 0.01 {
                write!(attrs, r#" tuning="{}""#, zone.tune_cents as i32).unwrap();
            }

            if zone.sample_start > 0 {
                write!(attrs, r#" start="{}""#, zone.sample_start).unwrap();
            }
            if let Some(end) = zone.sample_end {
                write!(attrs, r#" end="{}""#, end).unwrap();
            }

            if let Some(ref loop_info) = zone.loop_info {
                if loop_info.mode != LoopMode::None {
                    write!(
                        attrs,
                        r#" loopStart="{}" loopEnd="{}" loopEnabled="true""#,
                        loop_info.start, loop_info.end
                    )
                    .unwrap();
                    if loop_info.crossfade > 0 {
                        write!(attrs, r#" loopCrossfade="{}""#, loop_info.crossfade).unwrap();
                    }
                }
            }

            if zone.round_robin > 0 {
                write!(attrs, r#" seqPosition="{}""#, zone.round_robin).unwrap();
            }

            writeln!(xml, r#"      <sample {attrs} />"#).unwrap();
        }

        writeln!(xml, r#"    </group>"#).unwrap();
    }

    writeln!(xml, r#"  </groups>"#).unwrap();
    writeln!(xml, r#"</DecentSampler>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn generate_valid_xml() {
        let inst = Instrument::builder("Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();
        let xml = generate_dspreset(&inst);
        assert!(xml.contains("<DecentSampler>"));
        assert!(xml.contains(r#"rootNote="60""#));
        assert!(xml.contains(r#"path="samples/C4.wav""#));
    }
}
