use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::format::ExportFormat;

use crate::model::Instrument;
use crate::traits::{ExportError, FormatExporter};
use crate::util::sanitize_filename;

/// Exports instruments to Akai MPC Keygroup Program (.xpm) format.
///
/// The MPC Keygroup format is an XML-based program file that defines
/// keygroups with up to 4 layers each. Compatible with MPC One/Live/X.
pub struct MpcKeygroupExporter;

impl FormatExporter for MpcKeygroupExporter {
    fn format(&self) -> ExportFormat {
        ExportFormat::MpcKeygroup
    }

    fn name(&self) -> &str {
        "MPC Keygroup"
    }

    fn samples_subdir(&self) -> Option<&'static str> {
        Some("Samples")
    }

    fn export(&self, instrument: &Instrument, output_dir: &Path) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        std::fs::create_dir_all(&dir)?;

        let xml = generate_xpm(instrument);
        let filename = format!("{}.xpm", sanitize_filename(&instrument.name));
        std::fs::write(dir.join(filename), xml)?;

        Ok(())
    }
}

fn generate_xpm(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples -->"#).unwrap();
    writeln!(xml, r#"<MPCVObject>"#).unwrap();
    writeln!(xml, r#"  <Version>1.2</Version>"#).unwrap();
    writeln!(xml, r#"  <FileType>Keygroup</FileType>"#).unwrap();
    writeln!(xml, r#"  <ProgramName>{}</ProgramName>"#, instrument.name).unwrap();
    writeln!(xml, r#"  <Keygroups>"#).unwrap();

    let mut kg_index = 0;
    for group in &instrument.groups {
        for zone in &group.zones {
            writeln!(xml, r#"    <Keygroup>"#).unwrap();
            writeln!(xml, r#"      <Number>{}</Number>"#, kg_index).unwrap();
            writeln!(xml, r#"      <LowNote>{}</LowNote>"#, zone.key_low).unwrap();
            writeln!(xml, r#"      <HighNote>{}</HighNote>"#, zone.key_high).unwrap();
            writeln!(xml, r#"      <RootNote>{}</RootNote>"#, zone.root_note).unwrap();
            writeln!(
                xml,
                r#"      <SemiToneDetune>{}</SemiToneDetune>"#,
                (zone.tune_cents / 100.0) as i32
            )
            .unwrap();
            writeln!(
                xml,
                r#"      <FineTuneDetune>{}</FineTuneDetune>"#,
                (zone.tune_cents % 100.0) as i32
            )
            .unwrap();
            writeln!(xml, r#"      <Layers>"#).unwrap();
            writeln!(xml, r#"        <Layer>"#).unwrap();
            writeln!(xml, r#"          <Number>0</Number>"#).unwrap();
            writeln!(
                xml,
                r#"          <SampleName>Samples/{}</SampleName>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(
                xml,
                r#"          <VelocityStart>{}</VelocityStart>"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"          <VelocityEnd>{}</VelocityEnd>"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"          <Volume>{:.1}</Volume>"#, zone.gain_db).unwrap();
            writeln!(xml, r#"        </Layer>"#).unwrap();
            writeln!(xml, r#"      </Layers>"#).unwrap();
            writeln!(xml, r#"    </Keygroup>"#).unwrap();
            kg_index += 1;
        }
    }

    writeln!(xml, r#"  </Keygroups>"#).unwrap();
    writeln!(xml, r#"  <KeygroupCount>{}</KeygroupCount>"#, kg_index).unwrap();
    writeln!(xml, r#"</MPCVObject>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn export_creates_xpm() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("MPC Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        MpcKeygroupExporter.export(&inst, dir.path()).unwrap();

        let xpm = dir.path().join("MPC Test").join("MPC Test.xpm");
        assert!(xpm.exists());

        let content = std::fs::read_to_string(&xpm).unwrap();
        assert!(content.contains("<MPCVObject>"));
        assert!(content.contains("<FileType>Keygroup</FileType>"));
        assert!(content.contains("<RootNote>60</RootNote>"));
    }
}
