// Preserve source exporter implementation during extraction.
#![allow(clippy::collapsible_if)]

use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::model::Instrument;
use crate::traits::ExportError;
use crate::util::sanitize_filename;

/// Exports instruments to Reason NN-XT XML patch format.
///
/// The NN-XT is a sample-playback synthesizer in Propellerhead Reason.
/// This exporter produces an XML-based patch file (`.sxt`) alongside a
/// samples directory. Each zone is mapped as a key zone within the patch.
pub struct NnxtExporter;

impl NnxtExporter {
    pub fn export_nnxt(
        &self,
        instrument: &Instrument,
        output_dir: &Path,
    ) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        let samples_dir = dir.join("Samples");
        std::fs::create_dir_all(&samples_dir)?;

        let xml = generate_nnxt_patch(instrument);
        let filename = format!("{}.sxt", sanitize_filename(&instrument.name));
        std::fs::write(dir.join(filename), xml)?;

        Ok(())
    }
}

fn generate_nnxt_patch(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(
        xml,
        r#"<!-- Generated by Multisamples for Reason NN-XT -->"#
    )
    .unwrap();
    writeln!(xml, r#"<NNXTPatch>"#).unwrap();
    writeln!(xml, r#"  <name>{}</name>"#, instrument.name).unwrap();
    writeln!(xml, r#"  <version>1.0</version>"#).unwrap();
    writeln!(xml, r#"  <globalParameters>"#).unwrap();
    writeln!(xml, r#"    <polyphony>16</polyphony>"#).unwrap();
    writeln!(xml, r#"    <filterFreq>127</filterFreq>"#).unwrap();
    writeln!(xml, r#"  </globalParameters>"#).unwrap();
    writeln!(xml, r#"  <keyMap>"#).unwrap();

    let mut zone_index = 0;
    for group in &instrument.groups {
        writeln!(xml, r#"    <group name="{}">"#, group.name).unwrap();

        for zone in &group.zones {
            writeln!(xml, r#"      <keyZone>"#).unwrap();
            writeln!(xml, r#"        <index>{}</index>"#, zone_index).unwrap();
            writeln!(
                xml,
                r#"        <samplePath>Samples/{}</samplePath>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(xml, r#"        <rootNote>{}</rootNote>"#, zone.root_note).unwrap();
            writeln!(xml, r#"        <lowNote>{}</lowNote>"#, zone.key_low).unwrap();
            writeln!(xml, r#"        <highNote>{}</highNote>"#, zone.key_high).unwrap();
            writeln!(
                xml,
                r#"        <lowVelocity>{}</lowVelocity>"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"        <highVelocity>{}</highVelocity>"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"        <volume>{:.1}</volume>"#, zone.gain_db).unwrap();
            writeln!(xml, r#"        <tune>{:.1}</tune>"#, zone.tune_cents).unwrap();

            if let Some(ref li) = zone.loop_info {
                if li.mode != crate::model::LoopMode::None {
                    writeln!(xml, r#"        <loop>"#).unwrap();
                    writeln!(xml, r#"          <start>{}</start>"#, li.start).unwrap();
                    writeln!(xml, r#"          <end>{}</end>"#, li.end).unwrap();
                    writeln!(
                        xml,
                        r#"          <mode>{}</mode>"#,
                        match li.mode {
                            crate::model::LoopMode::Forward => "forward",
                            crate::model::LoopMode::Backward => "backward",
                            crate::model::LoopMode::PingPong => "alternating",
                            crate::model::LoopMode::None => "off",
                        }
                    )
                    .unwrap();
                    writeln!(xml, r#"        </loop>"#).unwrap();
                }
            }

            writeln!(xml, r#"      </keyZone>"#).unwrap();
            zone_index += 1;
        }

        writeln!(xml, r#"    </group>"#).unwrap();
    }

    writeln!(xml, r#"  </keyMap>"#).unwrap();
    writeln!(xml, r#"  <zoneCount>{}</zoneCount>"#, zone_index).unwrap();
    writeln!(xml, r#"</NNXTPatch>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn export_creates_nnxt_patch() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("NNXT Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        let exporter = NnxtExporter;
        exporter.export_nnxt(&inst, dir.path()).unwrap();

        let patch = dir.path().join("NNXT Test").join("NNXT Test.sxt");
        assert!(patch.exists());

        let content = std::fs::read_to_string(&patch).unwrap();
        assert!(content.contains("<NNXTPatch>"));
        assert!(content.contains("<rootNote>60</rootNote>"));
        assert!(content.contains("<zoneCount>1</zoneCount>"));
    }
}
