use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::format::ExportFormat;

use crate::model::{Instrument, LoopMode};
use crate::traits::{ExportError, FormatExporter};
use crate::util::sanitize_filename;

/// Exports instruments to SFZ format.
pub struct SfzExporter;

impl FormatExporter for SfzExporter {
    fn format(&self) -> ExportFormat {
        ExportFormat::Sfz
    }

    fn name(&self) -> &str {
        "SFZ"
    }

    fn export(&self, instrument: &Instrument, output_dir: &Path) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        std::fs::create_dir_all(&dir)?;

        let sfz_content = generate_sfz(instrument);
        let sfz_path = dir.join(format!("{}.sfz", sanitize_filename(&instrument.name)));
        std::fs::write(&sfz_path, sfz_content)?;

        Ok(())
    }
}

fn generate_sfz(instrument: &Instrument) -> String {
    let mut out = String::new();

    // Header comment
    writeln!(out, "// SFZ file generated by Multisamples").unwrap();
    writeln!(out, "// Instrument: {}", instrument.name).unwrap();
    if !instrument.vendor.is_empty() {
        writeln!(out, "// Vendor: {}", instrument.vendor).unwrap();
    }
    writeln!(out).unwrap();

    // Global settings
    writeln!(out, "<control>").unwrap();
    writeln!(out, "default_path=samples/").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "<global>").unwrap();
    writeln!(out, "ampeg_release=0.5").unwrap();
    writeln!(out).unwrap();

    for group in &instrument.groups {
        writeln!(out, "<group>").unwrap();
        if !group.name.is_empty() {
            writeln!(out, "group_label={}", group.name).unwrap();
        }
        if group.velocity_low > 0 || group.velocity_high < 127 {
            writeln!(out, "lovel={}", group.velocity_low).unwrap();
            writeln!(out, "hivel={}", group.velocity_high).unwrap();
        }
        writeln!(out).unwrap();

        for zone in &group.zones {
            writeln!(out, "<region>").unwrap();
            writeln!(out, "sample={}", zone.sample_path.display()).unwrap();
            writeln!(out, "pitch_keycenter={}", zone.root_note).unwrap();
            writeln!(out, "lokey={}", zone.key_low).unwrap();
            writeln!(out, "hikey={}", zone.key_high).unwrap();

            if zone.velocity_low > 0 || zone.velocity_high < 127 {
                writeln!(out, "lovel={}", zone.velocity_low).unwrap();
                writeln!(out, "hivel={}", zone.velocity_high).unwrap();
            }

            if (zone.gain_db).abs() > 0.01 {
                writeln!(out, "volume={:.1}", zone.gain_db).unwrap();
            }

            if (zone.tune_cents).abs() > 0.01 {
                writeln!(out, "tune={}", zone.tune_cents as i32).unwrap();
            }

            if let Some(loop_info) = &zone.loop_info {
                match loop_info.mode {
                    LoopMode::Forward => writeln!(out, "loop_mode=loop_continuous").unwrap(),
                    LoopMode::Backward => writeln!(out, "loop_mode=loop_reverse").unwrap(),
                    LoopMode::PingPong => writeln!(out, "loop_mode=loop_sustain").unwrap(),
                    LoopMode::None => {}
                }
                if loop_info.mode != LoopMode::None {
                    writeln!(out, "loop_start={}", loop_info.start).unwrap();
                    writeln!(out, "loop_end={}", loop_info.end).unwrap();
                    if loop_info.crossfade > 0 {
                        writeln!(out, "loop_crossfade={}", loop_info.crossfade).unwrap();
                    }
                }
            }

            if zone.sample_start > 0 {
                writeln!(out, "offset={}", zone.sample_start).unwrap();
            }
            if let Some(end) = zone.sample_end {
                writeln!(out, "end={}", end).unwrap();
            }

            if zone.round_robin > 0 {
                writeln!(out, "seq_position={}", zone.round_robin).unwrap();
            }

            writeln!(out).unwrap();
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    fn test_instrument() -> Instrument {
        Instrument::builder("Test Piano")
            .vendor("Test Vendor")
            .group(Group {
                name: "Layer 1".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4_v127.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build()
    }

    #[test]
    fn generate_sfz_content() {
        let sfz = generate_sfz(&test_instrument());
        assert!(sfz.contains("sample=C4_v127.wav"));
        assert!(sfz.contains("pitch_keycenter=60"));
        assert!(sfz.contains("lokey=54"));
        assert!(sfz.contains("hikey=66"));
    }

    #[test]
    fn export_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let exporter = SfzExporter;
        exporter.export(&test_instrument(), dir.path()).unwrap();

        let sfz_file = dir.path().join("Test Piano").join("Test Piano.sfz");
        assert!(sfz_file.exists());
    }
}
