// Preserve source exporter implementation during extraction.
#![allow(clippy::collapsible_if)]

use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::model::Instrument;
use crate::traits::ExportError;
use crate::util::sanitize_filename;

/// Exports instruments to TAL-Sampler XML preset format.
///
/// TAL-Sampler uses an XML-based preset format with multi-layer sample
/// mappings. Each layer maps a WAV file across a key and velocity range.
/// This exporter produces a `.talsmpl` preset alongside a samples directory.
pub struct TalExporter;

impl TalExporter {
    pub fn export_tal(
        &self,
        instrument: &Instrument,
        output_dir: &Path,
    ) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        let samples_dir = dir.join("samples");
        std::fs::create_dir_all(&samples_dir)?;

        let xml = generate_tal_preset(instrument);
        let filename = format!("{}.talsmpl", sanitize_filename(&instrument.name));
        std::fs::write(dir.join(filename), xml)?;

        Ok(())
    }
}

fn generate_tal_preset(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples for TAL-Sampler -->"#).unwrap();
    writeln!(xml, r#"<TALSamplerPreset>"#).unwrap();
    writeln!(xml, r#"  <name>{}</name>"#, instrument.name).unwrap();
    writeln!(xml, r#"  <version>1.0</version>"#).unwrap();
    writeln!(xml, r#"  <layers>"#).unwrap();

    let mut layer_index = 0;
    for group in &instrument.groups {
        for zone in &group.zones {
            writeln!(xml, r#"    <layer>"#).unwrap();
            writeln!(xml, r#"      <index>{}</index>"#, layer_index).unwrap();
            writeln!(
                xml,
                r#"      <sample>samples/{}</sample>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(xml, r#"      <rootNote>{}</rootNote>"#, zone.root_note).unwrap();
            writeln!(xml, r#"      <lowNote>{}</lowNote>"#, zone.key_low).unwrap();
            writeln!(xml, r#"      <highNote>{}</highNote>"#, zone.key_high).unwrap();
            writeln!(
                xml,
                r#"      <lowVelocity>{}</lowVelocity>"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"      <highVelocity>{}</highVelocity>"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"      <gain>{:.1}</gain>"#, zone.gain_db).unwrap();
            writeln!(xml, r#"      <tune>{:.1}</tune>"#, zone.tune_cents).unwrap();

            if let Some(ref li) = zone.loop_info {
                if li.mode != crate::model::LoopMode::None {
                    writeln!(xml, r#"      <loop>"#).unwrap();
                    writeln!(xml, r#"        <start>{}</start>"#, li.start).unwrap();
                    writeln!(xml, r#"        <end>{}</end>"#, li.end).unwrap();
                    writeln!(
                        xml,
                        r#"        <mode>{}</mode>"#,
                        match li.mode {
                            crate::model::LoopMode::Forward => "forward",
                            crate::model::LoopMode::Backward => "backward",
                            crate::model::LoopMode::PingPong => "pingpong",
                            crate::model::LoopMode::None => "none",
                        }
                    )
                    .unwrap();
                    writeln!(xml, r#"      </loop>"#).unwrap();
                }
            }

            writeln!(xml, r#"    </layer>"#).unwrap();
            layer_index += 1;
        }
    }

    writeln!(xml, r#"  </layers>"#).unwrap();
    writeln!(xml, r#"  <layerCount>{}</layerCount>"#, layer_index).unwrap();
    writeln!(xml, r#"</TALSamplerPreset>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn export_creates_tal_preset() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("TAL Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        let exporter = TalExporter;
        exporter.export_tal(&inst, dir.path()).unwrap();

        let preset = dir.path().join("TAL Test").join("TAL Test.talsmpl");
        assert!(preset.exists());

        let content = std::fs::read_to_string(&preset).unwrap();
        assert!(content.contains("<TALSamplerPreset>"));
        assert!(content.contains("<rootNote>60</rootNote>"));
        assert!(content.contains("<layerCount>1</layerCount>"));
    }
}
