use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::model::Instrument;
use crate::traits::ExportError;
use crate::util::sanitize_filename;

/// Exports instruments for 1010music devices (Blackbox, Bluebox, Nanobox).
///
/// Writes `preset.xml` and creates an empty `samples` directory.
/// This inherent export method does not copy WAVs; callers copy them separately.
pub struct Ten10MusicExporter;

// 1010music is not in ExportFormat enum yet, so we'll use WavBundle as a stand-in
// In practice, this would need its own variant. For now, this module provides
// the generation logic that can be called directly.

impl Ten10MusicExporter {
    pub fn export_1010(
        &self,
        instrument: &Instrument,
        output_dir: &Path,
    ) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        let samples_dir = dir.join("samples");
        std::fs::create_dir_all(&samples_dir)?;

        let xml = generate_preset_xml(instrument);
        std::fs::write(dir.join("preset.xml"), xml)?;

        Ok(())
    }
}

fn generate_preset_xml(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples for 1010music -->"#).unwrap();
    writeln!(xml, r#"<preset>"#).unwrap();
    writeln!(xml, r#"  <name>{}</name>"#, instrument.name).unwrap();
    writeln!(xml, r#"  <type>multi</type>"#).unwrap();
    writeln!(xml, r#"  <slices>"#).unwrap();

    for group in &instrument.groups {
        for zone in &group.zones {
            writeln!(xml, r#"    <slice>"#).unwrap();
            writeln!(
                xml,
                r#"      <file>samples/{}</file>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(xml, r#"      <rootNote>{}</rootNote>"#, zone.root_note).unwrap();
            writeln!(xml, r#"      <lowNote>{}</lowNote>"#, zone.key_low).unwrap();
            writeln!(xml, r#"      <highNote>{}</highNote>"#, zone.key_high).unwrap();
            writeln!(
                xml,
                r#"      <lowVelocity>{}</lowVelocity>"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"      <highVelocity>{}</highVelocity>"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"      <gain>{:.1}</gain>"#, zone.gain_db).unwrap();
            writeln!(xml, r#"      <tune>{:.1}</tune>"#, zone.tune_cents).unwrap();
            writeln!(xml, r#"    </slice>"#).unwrap();
        }
    }

    writeln!(xml, r#"  </slices>"#).unwrap();
    writeln!(xml, r#"</preset>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn export_creates_preset_xml() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("1010 Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        let exporter = Ten10MusicExporter;
        exporter.export_1010(&inst, dir.path()).unwrap();

        let preset = dir.path().join("1010 Test").join("preset.xml");
        assert!(preset.exists());

        let content = std::fs::read_to_string(&preset).unwrap();
        assert!(content.contains("<preset>"));
        assert!(content.contains("<type>multi</type>"));
        assert!(content.contains("<rootNote>60</rootNote>"));
    }
}
