// Preserve source exporter implementation during extraction.
#![allow(clippy::collapsible_if)]

use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::model::Instrument;
use crate::traits::ExportError;
use crate::util::sanitize_filename;

/// Exports instruments to TX16Wx Software Sampler XML preset format.
///
/// TX16Wx uses an XML-based preset format (`.txprog`) with sample references
/// organized into groups and key zones. Each zone maps a sample across a
/// key and velocity range with tuning and gain parameters.
pub struct Tx16wxExporter;

impl Tx16wxExporter {
    pub fn export_tx16wx(
        &self,
        instrument: &Instrument,
        output_dir: &Path,
    ) -> Result<(), ExportError> {
        let dir = output_dir.join(sanitize_filename(&instrument.name));
        let samples_dir = dir.join("Samples");
        std::fs::create_dir_all(&samples_dir)?;

        let xml = generate_tx16wx_preset(instrument);
        let filename = format!("{}.txprog", sanitize_filename(&instrument.name));
        std::fs::write(dir.join(filename), xml)?;

        Ok(())
    }
}

fn generate_tx16wx_preset(instrument: &Instrument) -> String {
    let mut xml = String::new();

    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#).unwrap();
    writeln!(xml, r#"<!-- Generated by Multisamples for TX16Wx -->"#).unwrap();
    writeln!(xml, r#"<TX16WxProgram>"#).unwrap();
    writeln!(xml, r#"  <name>{}</name>"#, instrument.name).unwrap();
    writeln!(xml, r#"  <version>3.0</version>"#).unwrap();
    writeln!(xml, r#"  <author>{}</author>"#, instrument.vendor).unwrap();
    writeln!(xml, r#"  <category>{}</category>"#, instrument.category).unwrap();
    writeln!(xml, r#"  <groups>"#).unwrap();

    let mut group_index = 0;
    let mut total_zones = 0;
    for group in &instrument.groups {
        writeln!(xml, r#"    <group>"#).unwrap();
        writeln!(xml, r#"      <index>{}</index>"#, group_index).unwrap();
        writeln!(xml, r#"      <name>{}</name>"#, group.name).unwrap();
        writeln!(xml, r#"      <keyZones>"#).unwrap();

        for zone in &group.zones {
            writeln!(xml, r#"        <keyZone>"#).unwrap();
            writeln!(
                xml,
                r#"          <sample>Samples/{}</sample>"#,
                zone.sample_path.display()
            )
            .unwrap();
            writeln!(xml, r#"          <rootKey>{}</rootKey>"#, zone.root_note).unwrap();
            writeln!(xml, r#"          <lowKey>{}</lowKey>"#, zone.key_low).unwrap();
            writeln!(xml, r#"          <highKey>{}</highKey>"#, zone.key_high).unwrap();
            writeln!(
                xml,
                r#"          <lowVelocity>{}</lowVelocity>"#,
                zone.velocity_low
            )
            .unwrap();
            writeln!(
                xml,
                r#"          <highVelocity>{}</highVelocity>"#,
                zone.velocity_high
            )
            .unwrap();
            writeln!(xml, r#"          <gain>{:.1}</gain>"#, zone.gain_db).unwrap();
            writeln!(
                xml,
                r#"          <coarseTune>{}</coarseTune>"#,
                (zone.tune_cents / 100.0) as i32
            )
            .unwrap();
            writeln!(
                xml,
                r#"          <fineTune>{}</fineTune>"#,
                (zone.tune_cents % 100.0) as i32
            )
            .unwrap();

            if let Some(ref li) = zone.loop_info {
                if li.mode != crate::model::LoopMode::None {
                    writeln!(xml, r#"          <loop>"#).unwrap();
                    writeln!(xml, r#"            <start>{}</start>"#, li.start).unwrap();
                    writeln!(xml, r#"            <end>{}</end>"#, li.end).unwrap();
                    writeln!(
                        xml,
                        r#"            <crossfade>{}</crossfade>"#,
                        li.crossfade
                    )
                    .unwrap();
                    writeln!(
                        xml,
                        r#"            <mode>{}</mode>"#,
                        match li.mode {
                            crate::model::LoopMode::Forward => "forward",
                            crate::model::LoopMode::Backward => "backward",
                            crate::model::LoopMode::PingPong => "pingpong",
                            crate::model::LoopMode::None => "off",
                        }
                    )
                    .unwrap();
                    writeln!(xml, r#"          </loop>"#).unwrap();
                }
            }

            if zone.round_robin > 0 {
                writeln!(
                    xml,
                    r#"          <roundRobin>{}</roundRobin>"#,
                    zone.round_robin
                )
                .unwrap();
            }

            writeln!(xml, r#"        </keyZone>"#).unwrap();
            total_zones += 1;
        }

        writeln!(xml, r#"      </keyZones>"#).unwrap();
        writeln!(xml, r#"    </group>"#).unwrap();
        group_index += 1;
    }

    writeln!(xml, r#"  </groups>"#).unwrap();
    writeln!(xml, r#"  <groupCount>{}</groupCount>"#, group_index).unwrap();
    writeln!(xml, r#"  <zoneCount>{}</zoneCount>"#, total_zones).unwrap();
    writeln!(xml, r#"</TX16WxProgram>"#).unwrap();

    xml
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Group, Zone};
    use std::path::PathBuf;

    #[test]
    fn export_creates_tx16wx_preset() {
        let dir = tempfile::tempdir().unwrap();
        let inst = Instrument::builder("TX16Wx Test")
            .group(Group {
                name: "Main".into(),
                key_low: 0,
                key_high: 127,
                velocity_low: 0,
                velocity_high: 127,
                zones: vec![Zone {
                    sample_path: PathBuf::from("C4.wav"),
                    root_note: 60,
                    key_low: 54,
                    key_high: 66,
                    velocity_low: 0,
                    velocity_high: 127,
                    gain_db: 0.0,
                    tune_cents: 0.0,
                    loop_info: None,
                    sample_start: 0,
                    sample_end: None,
                    round_robin: 0,
                }],
            })
            .build();

        let exporter = Tx16wxExporter;
        exporter.export_tx16wx(&inst, dir.path()).unwrap();

        let preset = dir.path().join("TX16Wx Test").join("TX16Wx Test.txprog");
        assert!(preset.exists());

        let content = std::fs::read_to_string(&preset).unwrap();
        assert!(content.contains("<TX16WxProgram>"));
        assert!(content.contains("<rootKey>60</rootKey>"));
        assert!(content.contains("<zoneCount>1</zoneCount>"));
        assert!(content.contains("<groupCount>1</groupCount>"));
    }
}
